#!/usr/bin/python
# -*- coding: utf-8 -*-

import argparse
import os

parser = argparse.ArgumentParser()
parser.add_argument("-l", "--list", help="File of branches list with its repo",
                    default="/home/yanina/vauxoo/tools/squash/squash.txt")
parser.add_argument("-pl", "--pull", help="Update git pull ... each branch",
                    action="store_true")
parser.add_argument("-ps", "--push", help="Update git push ... each branch",
                    action="store_true")
parser.add_argument("-cl", "--clean", help="Clean execute, "
                    "files and directory ... each branch",
                    action="store_true")
parser.add_argument("-cp", "--copy", help="Copy, "
                    "files and directory into rma",
                    action="store_true")
parser.add_argument("-li", "--lint", help="Copy, "
                    "files and directory into rma",
                    action="store_true")
args = parser.parse_args()

source_path = os.getcwd()
with open(args.list, "r") as branches:
    for info in branches:
        info = info.strip()
        repo, branch, module = info.split()[0], info.split()[1], False
        os.chdir(branch)
        if len(info.split()) == 3:
            module = info.split()[2]

        print "#" * 75
        print "*" * 75
        os.system("git status")

        if args.pull:
            os.system("git branch")
            os.system("git pull %s %s" % (repo, branch) )

        if args.push:
            os.system("git branch")
            os.system("git push %s %s" % (repo, branch) )

        if args.clean:
            os.system("git clean -xfd")

        if args.copy:
            if module:
                os.system("cp %s /home/yanina/vauxoo/public_addons/rma -r" % module)

        if args.lint:
            base_path = "~/vauxoo/public_addons/maintainer-quality-tools/travis/"
            if module:
                os.system("flake8 %s --config=%scfg/travis_run_flake8__init__.cfg --ignore=F401" % (module,base_path))
                os.system("%stest_odoo_lint --path %s" % (base_path,module))
                os.system("%srun_pylint.py --config-file %scfg/travis_run_pylint_pr.cfg --path %s/" % (base_path,base_path,module))

        print "*" * 75
        print "#" * 75
        os.chdir(source_path)
